spring:
  application:
    name: traffic
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/traffic
    username: postgres
    password: 1004

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

logging:
  level:
    com.example.traffic: debug